steps:
  # build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/dr-retail:$COMMIT_SHA",
        "./app/dr-retail/",
      ]
    # push the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/dr-retail:$COMMIT_SHA",
      ]
    # deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "$_SERVICE_NAME",
        "--image",
        "europe-west1-docker.pkg.dev/$_PROJECT_ID/cloud-run-source-deploy/dr-retail:$COMMIT_SHA",
        "--region",
        "europe-west1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
         
        
      ]
options:
  logging: CLOUD_LOGGING_ONLY
