clothing_keywords = [
                'wear', 'clothing', 'apparel', 'attire', 'garment', 'outfit', 'dress', 'shirt', 'pants',
                'hat', 'shoes', 'jacket', 'scarf', 'gloves', 'sunglasses', 'socks', 'tie', 'coat',
                'blouse', 'sweater', 'shorts', 'skirt', 'jeans', 'boots', 'sandals', 'sneakers',
                'hoodie', 'vest', 'robe', 'kimono', 'pajamas', 'leggings', 'tuxedo', 'overalls',
                'swimsuit', 'bikini', 'lingerie', 'trousers', 't-shirt', 'cap', 'visor', 'gown',
                'uniform', 'blazer', 'cardigan', 'trench coat', 'raincoat', 'poncho', 'tank top',
                'turtleneck', 'tights', 'sweatshirt', 'onesie', 'vest', 'waistcoat', 'hijab', 'headband',
                'bandana', 'mittens', 'gaiters', 'beanie', 'beret', 'fedora', 'top hat', 'baseball cap',
                'visor cap', 'crown', 'fascinator', 'sun hat', 'beach hat', 'sailor hat', 'bowler hat',
                'derby hat', 'bucket hat', 'panama hat', 'trilby hat', 'straw hat', 'bonnet', 'cloche hat',
                'cufflinks', 'suspenders', 'belt', 'sash', 'apron', 'vestment', 'kilt', 'caftan', 'toga',
                'Floral Fit and Flare dress', 'Floral printed long dress', 'Floral Sleeveless Fit & Flare dress',
                'Floral Print Fit & Flare dress', 'Sleeveless Net Fit & Flare dress', 'Glamorous Hot pink Trail dress',
                'Mark & Mia Sleeveless partywear Frock', 'Babyhug Sleeveless party Frock With Foil Print & Floral Corsage',
                'Girls Ombre Halter Neck layered party Wear Top with Pant', 'Foreverkidz Tulle & Net Bow love Evening Gown for Girls',
                'Flowers Embroidered And Faux Mirror Work Top With Attached Drape And lehenga', 'Casa Ninos lilac Off-shoulder Gown For Girls',
                'Foreverkidz Sequin & Tulle Ramp Glam Tail dress for Girls', 'Foreverkidz Tulle & Net lily party dress for Girls',
                'Maroon Floral Princess Gown', 'lilpicks Couture Full Sleeves Never Mind Text Placement Printed Crop Top With Coordinating Jogger',
                'lilpicks Couture half Sleeves Front Tie Up Solid Top With Stripped Palazzo', 'Babyhug 100% Cotton Singlet Sleeves Jumpsuit Floral Print',
                'Taffy Sleeveless Heart Shape Rhinestone Detail Crop Top & Short Skirt Set', 'Striped Fit & Flare Reversible dress',
                '2-piece patterned set', '2-piece sweatshirt set', 'Men navy Slim Fit Solid formal Three Piece Suit',
                'Men Grey Slim Fit Textured formal Two Piece Suit', 'Men blue Slim Fit Textured formal Three Piece Suit',
                'Men White Slim Fit Textured Full Sleeves casual shirts', 'Men navy Slim Fit Print party Two Piece Suit',
                'Men blue Slim Fit Stripe Full Sleeves formal shirts', 'Men blue Slim Fit Textured casual shirt',
                'Men navy Slim Fit Solid formal trouser', 'Men red Slim Fit Solid casual blazer', 'Men black Regular Fit Dark Wash jeans',
                'Men black Regular Fit Dark Wash jeans', 'Men Green Solid Slim-Fit Single-Breasted Formal Suit', 'Cloud Cream Patterned Sherwani Set',
                'blazer', 'wedding dress', 'saree', 'ball gown wedding dress', 'full sleeves stretch fit blazer & pant',
                'full sleeves striped blazer with basic printed tee', 'pure cotton smart tech t-shirt',
                'full sleeves asymmetrical kurta with pyjama', 'full sleeves party suit solid',
                'full sleeves button detailed zipper jacket with motorbike printed tee',
                'full sleeves seamless abstract motif printed 3 piece party set',
                'full sleeves mid double striped jacket with half sleeves text printed tee',
                'full sleeves solid party suits with waistcoat & bow tie',
                'full sleeves triple line distinct striped motif printed blazer',
                'full sleeves triple checkered blazer', 'set of 5 croc-embossed tote bags',
                'cotton lycra full sleeves checkered party suits with bow tie','checkered blazer'
                'full sleeves graph checkered blazer with exclusive style text printed tee & pant',
                'woven full sleeves solid party suit with bow','full sleeves','bracelet'
                'sterling silver blue topaz september birthstone bracelet rakhi',
                'wear', 'clothing', 'apparel', 'attire', 'garment', 'outfit', 'dress', 'shirt', 'pants',
                'hat', 'shoes', 'jacket', 'scarf', 'gloves', 'sunglasses', 'socks', 'tie', 'coat',
                'blazer', 'jeans', 't-shirt', 'jumpsuit', 'top', 'trouser', 'anarkali', 'saree', 'sherwani',
                'crop top', 'jacket', 'tunic', 'skirt', 'top & pant', 'layered top', 'singlet sleeves',
                'crop top & short skirt set', 'reversible dress', '2-piece patterned set', '2-piece sweatshirt set',
                'co-ord set', 'ombre top & pant set', 'party suit', 'casual shirt', 'full sleeves shirt',
                'half sleeves shirt', 'checkered shirt', 'striped shirt', 'solid shirt', 'formal trouser',
                'casual blazer', 'dark wash jeans', 'slim-fit suit', 'textured suit', 'textured shirt',
                'solid formal trouser', 'slim-fit blazer', 'regular fit jeans', 'full sleeves shirt & short skirt set',
                'solid party suits', 'half sleeves shirt & printed tee', 'solid casual blazer', 'regular fit trouser',
                'solid formal blazer', 'regular fit jeans','shoes', 'sneakers', 'boots', 'flats', 'heels', 'sandals', 
                'slippers', 'loafers', 'espadrilles', 'moccasins', 'oxfords', 'flip-flops', 'wedges', 'platforms', 
                'trainers', 'clogs', 'brogues', 'pumps', 'hiking boots', 'athletic shoes', 'mules', 'chukka boots', 
                'wellington boots', 'thong sandals', 'combat boots', 'water shoes', 'ski boots', 'skate shoes', 
                'jellies', 'penny loafers', 'espadrille wedges', 'ankle boots', 'mary janes', 'boat shoes', 'snow boots',
                'cowboy boots', 'socks', 'leg warmers', 'stockings', 'tights', 'gaiters', 'shoe insoles', 'boot trees', 'shoe horns',
                'pattern', 'formal wear','Pants','Top','body jewelry', 'pre-engagement ring', 'wedding ring', 'jewellery', 'engagement ring', 'ring', 
                'luggage and bags', 'bag', 'shoulder bag', 'handbag',  'hobo bag',  'fashion accessory', 'Bag', 'Handbag','hat','cap','silk',
                 'Jeans', 'Shirt',' ornament','walking shoe', 'sportswear',   'outdoor shoe', 'athletic shoe', 'pattern', 'carmine', 'sock', 'Footwear', 'Shoe','skate shoe','bride',
                 'textile','trousers','Coat','textile', 'tints and shades', 'linens', 'Top','glove','collar', 'blazer',  'suit','bridal party dress', 'Sandal',
            ]

            

            # Color keywords
color_keywords = [
                'red', 'blue', 'green', 'yellow', 'orange', 'purple', 'pink', 'brown', 'black', 'white','electric blue',
                'gray', 'silver', 'gold', 'beige', 'turquoise', 'maroon', 'indigo', 'teal', 'cream',
                'lavender', 'violet', 'cyan', 'magenta', 'olive', 'navy', 'peach', 'khaki', 'charcoal',
                'burgundy', 'coral', 'salmon', 'taupe', 'mauve', 'bronze', 'plum', 'fuchsia', 'russet',
                'White', 'Red', 'Magenta', 'Pink', 'Hot pink/ wine', 'Blue', 'Mint', 'Purple/blue/pink',
                'Lilac', 'Maroon', 'Green', 'Navy blue', 'Grey', 'Cream','cream', 'red', 'maroon', 'peach', 'black', 'pink', 'green', 'blue', 'navy blue', 'brown',
                'sky blue', 'gold', 
                 'white', 'red', 'pink', 'magenta', 'hot pink', 'blue', 'mint', 'lilac', 'green', 'grey',
                'beige', 'yellow', 'maroon', 'purple', 'navy blue', 'brown', 'black', 'orange', 'cream',
                'peach', 'lavender', 'sky blue', 'olive', 'teal', 'coral', 'turquoise', 'mustard', 'silver',
                'gold', 'rose gold', 'bronze', 'copper', 'platinum', 'pearl', 'ruby', 'emerald', 'sapphire',
                'amethyst', 'topaz', 'aquamarine', 'opal', 'garnet', 'onyx', 'quartz', 'peridot', 'tanzanite',
                'citrine', 'amber', 'jade', 'ruby red','azure'
            ]
